import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type { AppProps } from "next/app";
import { CssBaseline } from "@mui/material";
import { EmotionCache } from "@emotion/cache";
import { CacheProvider } from "@emotion/react";
import { createEmotionCache } from "@/utils";
import { MUIProvider } from "@/providers";
import "slick-carousel/slick/slick.css";
import "./assets/css/globals.css";
import "./assets/css/react-slick.css";
import { NextPageWithLayout } from "@/interfaces/layout";
import Header from "@/components/header";

// const clientSideEmotionCache = createEmotionCache();

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <MUIProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          {children}
        </body>
      </html>
    </MUIProvider>
  );
}
